"""Compressor - 压缩合并生成 Manifest + AGENTS.md"""

from datetime import datetime
from pathlib import Path
from typing import Optional

from skills_orchestrator.models import ResolvedConfig, Manifest, Zone


class Compressor:
    """压缩器 - 生成 AGENTS.md"""

    def __init__(self, resolved: ResolvedConfig, registry=None):
        self.resolved = resolved
        self._registry = registry  # 可选：传入后 forced skill 读取走 registry.get_content()，支持 base 继承合并

    def compress(self) -> Manifest:
        """压缩并生成 Manifest"""
        # 读取 forced skills 完整内容
        forced_content = self._read_forced_skills()

        # 生成 passive skills 摘要表格
        passive_index = self._generate_passive_index()

        # 收集 blocked skills ID
        blocked_list = [s.id for s in self.resolved.blocked_skills]

        return Manifest(
            forced_content=forced_content,
            passive_index=passive_index,
            blocked_list=blocked_list,
        )

    def generate_agents_md(self, manifest: Manifest, zone: Optional[Zone] = None) -> str:
        """生成 AGENTS.md 文件内容"""
        zone_id = zone.id if zone else "default"
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

        lines = [
            f"<!-- Generated by Skills Orchestrator v1.0 | Zone: {zone_id} | {timestamp} -->",
            "",
            "## Required Skills",
            "",
            "> 以下 skills 为强制加载，所有任务均须遵循。",
            "",
        ]

        # Required Skills 区（每个 skill 独立 --- 块）
        if manifest.forced_content:
            lines.append(manifest.forced_content)
        else:
            lines.append("> 当前 Zone 无强制 skills。")

        lines.append("")
        lines.append("## Available Skills")
        lines.append("")
        lines.append("> 以下 skills 按需选用。根据当前任务选择最相关的 skill 加载。")
        lines.append("")
        lines.append("| Skill | 说明 | Tags |")
        lines.append("|-------|------|------|")

        # Available Skills 区
        if manifest.passive_index:
            lines.append(manifest.passive_index)
        else:
            lines.append("> 当前 Zone 无可选 skills。")

        lines.append("")
        lines.append('如需使用某个 skill，请说明"使用 [skill-name] skill"，系统将加载完整内容。')

        return "\n".join(lines)

    def _resolve_path(self, skill_path: str) -> Path:
        """将 skill.path 解析为绝对路径（相对路径以 base_dir 为基准）。"""
        p = Path(skill_path)
        if p.is_absolute():
            return p
        return (Path(self.resolved.base_dir) / p).resolve()

    def _read_forced_skills(self) -> str:
        """读取 forced skills 完整内容，每个 skill 用 --- 块包裹。

        如果构造时传入了 registry，优先走 registry.get_content() 以支持 base 继承合并；
        否则直接读文件（兼容无 registry 的 CLI 场景）。
        """
        parts = []
        for skill in self.resolved.forced_skills:
            if self._registry:
                content = self._registry.get_content(skill.id) or f"> 文件不存在: {skill.path}"
            else:
                path = self._resolve_path(skill.path)
                content = (
                    path.read_text(encoding="utf-8") if path.exists() else f"> 文件不存在: {skill.path}"
                )
            stripped = content.strip()
            # 文件已有 frontmatter（--- 开头），不再双重包裹
            if stripped.startswith("---"):
                parts.append(stripped)
            else:
                parts.append(f"---\n{stripped}\n---")

        return "\n\n".join(parts)

    def _generate_passive_index(self) -> str:
        """生成 passive skills 摘要表格"""
        rows = []
        for skill in self.resolved.passive_skills:
            tags = ", ".join(skill.tags)
            rows.append(f"| {skill.name} | {skill.summary} | {tags} |")
        return "\n".join(rows)
