import json

from click.testing import CliRunner

from skills_orchestrator.evidence import export_evidence_bundle
from skills_orchestrator.main import cli
from skills_orchestrator.evidence_index import (
    build_multi_repo_artifacts,
    format_multi_repo_artifacts_json,
)
from skills_orchestrator.schema_validation import validate_document


def _workspace(tmp_path, repo_name: str, *, body: str = "# Skill\n"):
    repo = tmp_path / repo_name
    skills_dir = repo / "skills"
    config_dir = repo / "config"
    skills_dir.mkdir(parents=True)
    config_dir.mkdir()
    (skills_dir / "skill.md").write_text(
        "---\n"
        f"id: {repo_name}-skill\n"
        f"name: {repo_name.title()} Skill\n"
        f"summary: {repo_name} governed skill\n"
        "load_policy: require\n"
        "priority: 80\n"
        "owner: platform-team\n"
        f"source: internal://skills/{repo_name}-skill\n"
        "version: 1.0.0\n"
        "lifecycle: active\n"
        "approvers: [platform-team]\n"
        "---\n"
        f"{body}",
        encoding="utf-8",
    )
    config = config_dir / "skills.yaml"
    config.write_text(
        """
version: "2.0"
skill_dirs:
  - ../skills
zones:
  - id: default
    name: Default
    load_policy: free
    priority: 0
    rules: []
overrides: []
combos: []
""",
        encoding="utf-8",
    )
    (repo / "AGENTS.md").write_text(
        "<!-- Generated by Skills Orchestrator v4.7.7 | Zone: default -->\n",
        encoding="utf-8",
    )
    (repo / ".github" / "workflows").mkdir(parents=True)
    (repo / ".github" / "workflows" / "skills-orchestrator.yml").write_text(
        "name: SkillOps\njobs:\n  skillops:\n    steps:\n      - uses: BambooGap/skills-orchestrator@v4.7.7\n",
        encoding="utf-8",
    )
    return repo, config


def _evidence_manifest(tmp_path, repo_name: str):
    repo, config = _workspace(tmp_path, repo_name)
    evidence_dir = repo / "evidence"
    export_evidence_bundle(
        str(config),
        str(evidence_dir),
        policy_packs=["builtin/team-standard"],
        agents_md=str(repo / "AGENTS.md"),
    )
    return evidence_dir / "evidence-manifest.json"


def test_multi_repo_artifacts_index_summarizes_multiple_repositories(tmp_path):
    manifest_a = _evidence_manifest(tmp_path, "repo-a")
    manifest_b = _evidence_manifest(tmp_path, "repo-b")

    bundle = build_multi_repo_artifacts(
        [f"repo-b={manifest_b}", f"repo-a={manifest_a}"],
        scope_name="example",
        generated_at="2026-06-26T00:00:00Z",
    )

    assert bundle["schema_version"] == "skills-orchestrator.multi-repo-artifacts.v1"
    assert bundle["scope"] == {"kind": "multi-repo", "name": "example"}
    assert bundle["summary"]["repositories"] == 2
    assert bundle["summary"]["missing"] == 0
    assert bundle["summary"]["invalid"] == 0
    assert [repo["id"] for repo in bundle["repositories"]] == ["repo-a", "repo-b"]
    assert all(repo["ledger"]["bundle_hash"] for repo in bundle["repositories"])
    assert {artifact["repository_id"] for artifact in bundle["artifacts"]} == {"repo-a", "repo-b"}

    output = tmp_path / "multi-repo-artifacts.json"
    output.write_text(format_multi_repo_artifacts_json(bundle), encoding="utf-8")
    assert validate_document("multi-repo-artifacts", str(output)).valid is True


def test_multi_repo_artifacts_index_marks_missing_and_invalid_artifacts(tmp_path):
    manifest = _evidence_manifest(tmp_path, "repo-a")
    evidence_dir = manifest.parent
    (evidence_dir / "check.json").unlink()
    (evidence_dir / "doctor.json").write_text('{"tampered": true}\n', encoding="utf-8")

    bundle = build_multi_repo_artifacts(
        [f"repo-a={manifest}"],
        generated_at="2026-06-26T00:00:00Z",
    )

    statuses = {
        artifact["label"]: artifact["status"]
        for artifact in bundle["artifacts"]
        if artifact["repository_id"] == "repo-a"
    }
    assert statuses["check_json"] == "missing"
    assert statuses["doctor"] == "invalid"
    assert bundle["summary"]["missing"] == 1
    assert bundle["summary"]["invalid"] == 1


def test_multi_repo_artifacts_index_rejects_duplicate_repo_ids(tmp_path):
    manifest_a = _evidence_manifest(tmp_path, "repo-a")
    manifest_b = _evidence_manifest(tmp_path, "repo-b")

    try:
        build_multi_repo_artifacts([f"repo={manifest_a}", f"repo={manifest_b}"])
    except ValueError as exc:
        assert "Duplicate repository id(s) in evidence index: repo" in str(exc)
    else:
        raise AssertionError("duplicate repository ids should fail")


def test_evidence_index_cli_accepts_manifest_globs(tmp_path):
    _evidence_manifest(tmp_path, "repo-a")
    _evidence_manifest(tmp_path, "repo-b")
    output = tmp_path / "multi-repo-artifacts.json"
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "evidence",
            "index",
            "--manifest-glob",
            str(tmp_path / "repo-*" / "evidence" / "evidence-manifest.json"),
            "--scope-name",
            "example",
            "--output",
            str(output),
        ],
    )

    assert result.exit_code == 0
    payload = json.loads(output.read_text(encoding="utf-8"))
    assert payload["summary"]["repositories"] == 2
    assert validate_document("multi-repo-artifacts", str(output)).valid is True


def test_evidence_index_rejects_empty_inputs():
    runner = CliRunner()

    result = runner.invoke(cli, ["evidence", "index"])

    assert result.exit_code == 1
    assert "At least one --manifest or --manifest-glob input is required" in result.output
