import json

from click.testing import CliRunner

from skills_orchestrator.conformance import run_conformance
from skills_orchestrator.main import cli
from skills_orchestrator.schema_validation import validate_document


def _workspace(tmp_path):
    skills_dir = tmp_path / "skills"
    skills_dir.mkdir()
    (skills_dir / "review.md").write_text(
        "---\n"
        "id: review\n"
        "name: Review\n"
        "summary: Review skill\n"
        "owner: platform-team\n"
        "source: internal://skills/review\n"
        "version: 1.0.0\n"
        "lifecycle: active\n"
        "reviewed_at: 2026-06-21\n"
        "expires_at: 2999-01-01\n"
        "---\n"
        "# Review\n",
        encoding="utf-8",
    )
    config_dir = tmp_path / "config"
    config_dir.mkdir()
    config = config_dir / "skills.yaml"
    config.write_text(
        f"""
version: "2.0"
skill_dirs:
  - {skills_dir.resolve()}
zones:
  - id: default
    name: Default
    load_policy: free
    rules: []
""",
        encoding="utf-8",
    )
    (tmp_path / "AGENTS.md").write_text(
        "<!-- Generated by Skills Orchestrator v3.0.6 | Zone: default -->\n",
        encoding="utf-8",
    )
    (tmp_path / ".github" / "workflows").mkdir(parents=True)
    (tmp_path / ".github" / "workflows" / "skills-orchestrator.yml").write_text(
        "name: skillops\njobs:\n  check:\n    steps:\n      - run: skills-orchestrator check\n",
        encoding="utf-8",
    )
    return config


def _oversized_workspace(tmp_path):
    config = _workspace(tmp_path)
    skill_file = tmp_path / "skills" / "review.md"
    skill_file.write_text(
        skill_file.read_text(encoding="utf-8") + "\n" + ("x" * 21000), encoding="utf-8"
    )
    return config


def test_run_conformance_core_report_validates(tmp_path):
    config = _workspace(tmp_path)

    payload = run_conformance(
        str(config),
        project_root=str(tmp_path),
        policy_packs=["builtin/engineering-grade"],
    )
    report_file = tmp_path / "conformance.json"
    report_file.write_text(json.dumps(payload), encoding="utf-8")

    assert payload["status"] == "pass"
    assert payload["summary"]["failed"] == 0
    assert validate_document("conformance", str(report_file)).valid is True


def test_conformance_cli_json(tmp_path):
    config = _workspace(tmp_path)
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "conformance",
            "run",
            "--config",
            str(config),
            "--project-root",
            str(tmp_path),
            "--policy-pack",
            "builtin/engineering-grade",
            "--format",
            "json",
        ],
    )

    assert result.exit_code == 0
    payload = json.loads(result.output)
    assert payload["schema_version"] == "skills-orchestrator.conformance.v1"
    assert payload["status"] == "pass"


def test_conformance_fail_on_warning_does_not_fail_on_info_only(tmp_path):
    config = _oversized_workspace(tmp_path)
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "conformance",
            "run",
            "--config",
            str(config),
            "--project-root",
            str(tmp_path),
            "--fail-on",
            "warning",
        ],
    )

    assert result.exit_code == 0
    assert "SkillOps conformance: pass" in result.output
