import json

from click.testing import CliRunner

from skills_orchestrator.doctor import run_doctor
from skills_orchestrator.evidence import export_evidence_bundle
from skills_orchestrator.github_pr import (
    REGISTRY_DIFF_COMMENT_MARKER,
    format_registry_diff_comment,
)
from skills_orchestrator.main import cli
from skills_orchestrator.org_registry import (
    build_registry,
    diff_registries,
    format_registry_diff_markdown,
)
from skills_orchestrator.supply_chain import build_python_package_sbom
from skills_orchestrator.supply_chain import _runtime_requirement_name


def _workspace(tmp_path, *, owner: str = "platform-team", body: str = "# Skill\n"):
    tmp_path.mkdir(parents=True, exist_ok=True)
    skills_dir = tmp_path / "skills"
    skills_dir.mkdir()
    (skills_dir / "skill.md").write_text(
        "---\n"
        "id: team-skill\n"
        "name: Team Skill\n"
        "summary: Team skill\n"
        f"owner: {owner}\n"
        "source: internal://skills/team-skill\n"
        "version: 1.0.0\n"
        "lifecycle: active\n"
        "---\n"
        f"{body}",
        encoding="utf-8",
    )
    config_dir = tmp_path / "config"
    config_dir.mkdir()
    config = config_dir / "skills.yaml"
    config.write_text(
        f"""
version: "2.0"
skill_dirs:
  - {skills_dir.resolve()}
zones:
  - id: default
    name: Default
    load_policy: free
    rules: []
""",
        encoding="utf-8",
    )
    (tmp_path / "AGENTS.md").write_text(
        "<!-- Generated by Skills Orchestrator v2.4.0 | Zone: default -->\n",
        encoding="utf-8",
    )
    (tmp_path / ".github" / "workflows").mkdir(parents=True)
    (tmp_path / ".github" / "workflows" / "ci.yml").write_text(
        "name: ci\njobs:\n  skillops:\n    steps:\n      - uses: BambooGap/skills-orchestrator@v3\n",
        encoding="utf-8",
    )
    (tmp_path / "action.yml").write_text("name: action\n", encoding="utf-8")
    (tmp_path / "Dockerfile").write_text("FROM python:3.12-slim\n", encoding="utf-8")
    return config


def test_registry_build_summarizes_governed_skills(tmp_path):
    config = _workspace(tmp_path)

    registry = build_registry([str(config)])

    assert registry["schema_version"] == "skills-orchestrator.registry.v1"
    assert registry["summary"]["skill_refs"] == 1
    assert registry["owners"] == {"platform-team": 1}
    skill = registry["configs"][0]["skills"][0]
    assert skill["registry_key"]
    assert skill["governance"]["source"] == "internal://skills/team-skill"


def test_registry_diff_reports_governance_and_hash_changes(tmp_path):
    base_config = _workspace(tmp_path / "repo", owner="platform-team", body="# Skill\n")
    base = build_registry([str(base_config)])
    skill_file = tmp_path / "repo" / "skills" / "skill.md"
    skill_file.write_text(
        skill_file.read_text(encoding="utf-8").replace(
            "owner: platform-team\n", "owner: agent-platform\n"
        )
        + "\nChanged\n",
        encoding="utf-8",
    )
    head = build_registry([str(base_config)])

    diff = diff_registries(base, head)

    assert diff["summary"]["changed"] == 1
    assert diff["changed"][0]["id"] == "team-skill"
    assert {"content_hash", "governance"}.issubset(diff["changed"][0]["changes"])


def test_registry_diff_markdown_renders_pr_review_sections(tmp_path):
    base_config = _workspace(tmp_path / "repo", owner="platform-team", body="# Skill\n")
    base = build_registry([str(base_config)])
    skill_file = tmp_path / "repo" / "skills" / "skill.md"
    skill_file.write_text(
        skill_file.read_text(encoding="utf-8")
        .replace("owner: platform-team\n", "owner: agent-platform\n")
        .replace(
            "source: internal://skills/team-skill\n",
            "source: internal://skills/team-skill-v2\n",
        )
        .replace(
            "version: 1.0.0\n",
            "version: 1.0.1\n",
        )
        + "\nChanged\n",
        encoding="utf-8",
    )
    head = build_registry([str(base_config)])

    markdown = format_registry_diff_markdown(diff_registries(base, head))

    assert markdown.startswith("# Registry Diff\n")
    assert "## Summary" in markdown
    assert "| Changed | 1 |" in markdown
    assert "## Changed Skills" in markdown
    assert "content_hash" in markdown
    assert "owner platform-team -&gt; agent-platform" in markdown
    assert "source internal://skills/team-skill -&gt; internal://skills/team-skill-v2" in markdown
    assert "version 1.0.0 -&gt; 1.0.1" in markdown


def test_registry_diff_reports_duplicate_skill_entities(tmp_path):
    config_a = _workspace(tmp_path / "org" / "repo-a", body="# Skill\n")
    base = build_registry([str(config_a)])
    config_b = _workspace(
        tmp_path / "org" / "repo-b",
        owner="second-team",
        body="# Skill\nSecond copy\n",
    )

    head = build_registry([str(config_a), str(config_b)])
    diff = diff_registries(base, head)

    assert diff["summary"]["added"] == 1
    assert diff["summary"]["duplicate_id_changes"] == 1
    assert diff["added"][0]["id"] == "team-skill"
    assert diff["duplicate_id_changes"] == [{"id": "team-skill", "before": 1, "after": 2}]


def test_registry_cli_build_and_diff(tmp_path):
    config = _workspace(tmp_path / "repo", body="# Skill\n")
    base_file = tmp_path / "base.json"
    head_file = tmp_path / "head.json"
    runner = CliRunner()

    base_result = runner.invoke(
        cli,
        ["registry", "build", "--config-glob", str(config), "--output", str(base_file)],
    )
    skill_file = tmp_path / "repo" / "skills" / "skill.md"
    skill_file.write_text(skill_file.read_text(encoding="utf-8") + "\nChanged\n", encoding="utf-8")
    head_result = runner.invoke(
        cli,
        ["registry", "build", "--config-glob", str(config), "--output", str(head_file)],
    )
    diff_result = runner.invoke(
        cli, ["registry", "diff", str(base_file), str(head_file), "--format", "json"]
    )

    assert base_result.exit_code == 0
    assert head_result.exit_code == 0
    assert diff_result.exit_code == 0
    assert json.loads(diff_result.output)["summary"]["changed"] == 1


def test_registry_cli_diff_markdown_output_file(tmp_path):
    config = _workspace(tmp_path / "repo", body="# Skill\n")
    base_file = tmp_path / "base.json"
    head_file = tmp_path / "head.json"
    markdown_file = tmp_path / "diff.md"
    runner = CliRunner()

    base_result = runner.invoke(
        cli,
        ["registry", "build", "--config-glob", str(config), "--output", str(base_file)],
    )
    skill_file = tmp_path / "repo" / "skills" / "skill.md"
    skill_file.write_text(skill_file.read_text(encoding="utf-8") + "\nChanged\n", encoding="utf-8")
    head_result = runner.invoke(
        cli,
        ["registry", "build", "--config-glob", str(config), "--output", str(head_file)],
    )
    diff_result = runner.invoke(
        cli,
        [
            "registry",
            "diff",
            str(base_file),
            str(head_file),
            "--format",
            "markdown",
            "--output",
            str(markdown_file),
        ],
    )

    assert base_result.exit_code == 0
    assert head_result.exit_code == 0
    assert diff_result.exit_code == 0
    assert markdown_file.read_text(encoding="utf-8").startswith("# Registry Diff\n")


def test_registry_cli_diff_output_requires_force_for_existing_file(tmp_path):
    config = _workspace(tmp_path / "repo", body="# Skill\n")
    base_file = tmp_path / "base.json"
    head_file = tmp_path / "head.json"
    markdown_file = tmp_path / "diff.md"
    markdown_file.write_text("old\n", encoding="utf-8")
    runner = CliRunner()

    runner.invoke(
        cli, ["registry", "build", "--config-glob", str(config), "--output", str(base_file)]
    )
    skill_file = tmp_path / "repo" / "skills" / "skill.md"
    skill_file.write_text(skill_file.read_text(encoding="utf-8") + "\nChanged\n", encoding="utf-8")
    runner.invoke(
        cli, ["registry", "build", "--config-glob", str(config), "--output", str(head_file)]
    )

    result = runner.invoke(
        cli,
        [
            "registry",
            "diff",
            str(base_file),
            str(head_file),
            "--format",
            "markdown",
            "--output",
            str(markdown_file),
        ],
    )
    assert result.exit_code == 1
    assert markdown_file.read_text(encoding="utf-8") == "old\n"

    force_result = runner.invoke(
        cli,
        [
            "registry",
            "diff",
            str(base_file),
            str(head_file),
            "--format",
            "markdown",
            "--output",
            str(markdown_file),
            "--force",
        ],
    )

    assert force_result.exit_code == 0
    assert markdown_file.read_text(encoding="utf-8").startswith("# Registry Diff\n")


def test_registry_diff_markdown_noop_has_empty_sections(tmp_path):
    config = _workspace(tmp_path / "repo", body="# Skill\n")
    registry = build_registry([str(config)])

    markdown = format_registry_diff_markdown(diff_registries(registry, registry))

    assert "| Added | 0 |" in markdown
    assert markdown.count("No entries.") == 4


def test_registry_diff_comment_body_has_marker_and_footer():
    body = format_registry_diff_comment("# Registry Diff\n\n## Summary\n")

    assert body.startswith(REGISTRY_DIFF_COMMENT_MARKER)
    assert "Generated by `skills-orchestrator registry diff`" in body
    assert "hidden marker" in body


def test_registry_diff_comment_body_truncates_large_reports():
    body = format_registry_diff_comment("# Registry Diff\n\n" + ("row\n" * 1000), max_chars=1200)

    assert len(body) <= 1200
    assert body.startswith(REGISTRY_DIFF_COMMENT_MARKER)
    assert "truncated" in body


def test_registry_comment_body_cli_writes_file(tmp_path):
    markdown_file = tmp_path / "registry-diff.md"
    markdown_file.write_text("# Registry Diff\n\nNo entries.\n", encoding="utf-8")
    output_file = tmp_path / "comment.md"
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "registry",
            "comment-body",
            str(markdown_file),
            "--output",
            str(output_file),
        ],
    )

    assert result.exit_code == 0
    assert output_file.read_text(encoding="utf-8").startswith(REGISTRY_DIFF_COMMENT_MARKER)


def test_doctor_reports_readiness_payload(tmp_path, monkeypatch):
    config = _workspace(tmp_path)
    monkeypatch.chdir(tmp_path)

    payload = run_doctor(str(config), policy_packs=["builtin/team-standard"])

    assert payload["schema_version"] == "skills-orchestrator.doctor.v1"
    assert payload["profile"] == "adopter"
    assert payload["zone"] == "default"
    assert payload["summary"]["skills"] == 1
    assert payload["score"] > 0
    assert "ci_workflow" in payload["evidence"]
    assert "github_action" not in payload["evidence"]


def test_doctor_maintainer_profile_includes_release_artifacts(tmp_path, monkeypatch):
    config = _workspace(tmp_path)
    monkeypatch.chdir(tmp_path)

    payload = run_doctor(str(config), policy_packs=["builtin/team-standard"], profile="maintainer")

    assert payload["profile"] == "maintainer"
    assert "github_action" in payload["evidence"]
    assert "dockerfile" in payload["evidence"]
    assert "test_report" in payload["evidence"]


def test_init_team_standard_template_passes_adopter_doctor_threshold(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()

    init_result = runner.invoke(cli, ["init", "--template", "team-standard"])
    doctor_result = runner.invoke(cli, ["doctor", "--fail-under", "80", "--format", "json"])

    assert init_result.exit_code == 0
    assert doctor_result.exit_code == 0
    payload = json.loads(doctor_result.output)
    assert payload["profile"] == "adopter"
    assert payload["score"] >= 80
    assert payload["evidence"]["ci_workflow"]["present"] is True
    assert payload["evidence"]["ci_workflow"]["path"].endswith("skills-orchestrator.yml")
    assert not any(issue["id"] == "DOCTOR_CI_WORKFLOW" for issue in payload["issues"])


def test_doctor_resolves_relative_config_from_current_working_directory(tmp_path, monkeypatch):
    _workspace(tmp_path / "repo")
    monkeypatch.chdir(tmp_path)

    payload = run_doctor("repo/config/skills.yaml", policy_packs=["builtin/team-standard"])

    assert payload["evidence"]["ci_workflow"]["present"] is True
    assert not any(issue["id"] == "DOCTOR_CI_WORKFLOW" for issue in payload["issues"])


def test_doctor_cli_json(tmp_path, monkeypatch):
    config = _workspace(tmp_path)
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()

    result = runner.invoke(cli, ["doctor", "--config", str(config), "--format", "json"])

    assert result.exit_code == 0
    assert json.loads(result.output)["schema_version"] == "skills-orchestrator.doctor.v1"


def test_doctor_cli_maintainer_profile_json(tmp_path, monkeypatch):
    config = _workspace(tmp_path)
    monkeypatch.chdir(tmp_path)
    runner = CliRunner()

    result = runner.invoke(
        cli, ["doctor", "--config", str(config), "--profile", "maintainer", "--format", "json"]
    )

    assert result.exit_code == 0
    assert json.loads(result.output)["profile"] == "maintainer"


def test_evidence_export_writes_bundle(tmp_path, monkeypatch):
    config = _workspace(tmp_path)
    monkeypatch.chdir(tmp_path)
    out_dir = tmp_path / "evidence"

    bundle = export_evidence_bundle(
        str(config),
        str(out_dir),
        policy_packs=["builtin/team-standard"],
    )

    assert (out_dir / "check.json").exists()
    assert (out_dir / "check.sarif").exists()
    assert (out_dir / "instruction-manifest.json").exists()
    assert (out_dir / "policy-opa-input.json").exists()
    assert (out_dir / "doctor.json").exists()
    assert json.loads((out_dir / "evidence-manifest.json").read_text())["files"] == bundle["files"]


def test_integrations_cli_json():
    runner = CliRunner()

    result = runner.invoke(cli, ["integrations", "list", "--format", "json"])

    assert result.exit_code == 0
    payload = json.loads(result.output)
    ids = {integration["id"] for integration in payload["integrations"]}
    assert {"superpowers", "codegraph", "omnigent"}.issubset(ids)
    assert "/Users/" not in result.output


def test_python_package_sbom_uses_cyclonedx_shape():
    sbom = build_python_package_sbom(include_dependencies=False)

    assert sbom["bomFormat"] == "CycloneDX"
    assert sbom["specVersion"] == "1.5"
    assert sbom["serialNumber"].startswith("urn:uuid:")
    assert sbom["metadata"]["component"]["name"] == "skills-orchestrator"
    assert sbom["components"] == []


def test_runtime_requirement_name_skips_optional_extras():
    assert _runtime_requirement_name('pytest>=7.0; extra == "dev"') is None
    assert _runtime_requirement_name("pyyaml>=6.0") == "pyyaml"


def test_supply_chain_sbom_cli_writes_file(tmp_path):
    output_file = tmp_path / "package-sbom.cdx.json"
    runner = CliRunner()

    result = runner.invoke(
        cli,
        ["supply-chain", "sbom", "--no-dependencies", "--output", str(output_file)],
    )

    assert result.exit_code == 0
    payload = json.loads(output_file.read_text(encoding="utf-8"))
    assert payload["bomFormat"] == "CycloneDX"
