import json
from pathlib import Path

import pytest
from click.testing import CliRunner

from skills_orchestrator.adapters import inspect_adapters
from skills_orchestrator.adapters.scaffolds import export_claude_skill_bundles
from skills_orchestrator.checker import run_check
from skills_orchestrator.conformance import run_conformance
from skills_orchestrator.compiler import Parser, Resolver
from skills_orchestrator.compiler.instruction_manifest import build_instruction_manifest
from skills_orchestrator.evidence import export_evidence_bundle
from skills_orchestrator.explainability import (
    build_ci_explainability,
    format_ci_explainability_json,
)
from skills_orchestrator.formatters import format_diagnostics_json
from skills_orchestrator.formatters.manifest import format_instruction_manifest_json
from skills_orchestrator.main import cli
from skills_orchestrator.org_registry import build_registry, build_registry_graph, diff_registries
from skills_orchestrator.policy import build_opa_input
from skills_orchestrator.schema_validation import (
    list_schema_descriptors,
    load_schema,
    validate_document,
)
from skills_orchestrator.supply_chain import build_python_package_sbom, format_sbom_json
from skills_orchestrator.supply_chain import build_slsa_readiness, format_slsa_readiness_json


def _schema_workspace(tmp_path):
    skills_dir = tmp_path / "skills"
    skills_dir.mkdir()
    (skills_dir / "team.md").write_text(
        "---\n"
        "id: team-skill\n"
        "name: Team Skill\n"
        "summary: Team governed skill\n"
        "load_policy: require\n"
        "priority: 80\n"
        "owner: platform-team\n"
        "source: internal://skills/team-skill\n"
        "version: 1.0.0\n"
        "lifecycle: active\n"
        "approvers: [platform-team]\n"
        "---\n"
        "# Team Skill\n",
        encoding="utf-8",
    )
    config_dir = tmp_path / "config"
    config_dir.mkdir()
    config = config_dir / "skills.yaml"
    config.write_text(
        """
version: "2.0"
skill_dirs:
  - ../skills
zones:
  - id: default
    name: Default
    load_policy: free
    priority: 0
    rules: []
overrides: []
combos: []
""",
        encoding="utf-8",
    )
    (tmp_path / "AGENTS.md").write_text(
        "<!-- Generated by Skills Orchestrator v2.5.1 | Zone: default -->\n",
        encoding="utf-8",
    )
    (tmp_path / ".github" / "workflows").mkdir(parents=True)
    (tmp_path / ".github" / "workflows" / "ci.yml").write_text(
        "name: ci\njobs:\n  skillops:\n    steps:\n      - uses: BambooGap/skills-orchestrator@v3\n",
        encoding="utf-8",
    )
    (tmp_path / "action.yml").write_text("name: action\n", encoding="utf-8")
    (tmp_path / "Dockerfile").write_text("FROM python:3.12-slim\n", encoding="utf-8")
    return config


def test_schema_resources_are_packaged_and_loadable():
    kinds = {descriptor.kind for descriptor in list_schema_descriptors()}

    assert {
        "agent-handoff",
        "agent-runtime-image",
        "adapter-inspect",
        "check",
        "claude-skills-export",
        "ci-explainability",
        "config",
        "conformance",
        "container-provenance",
        "doctor",
        "evidence",
        "external-adoption-record",
        "enterprise-dashboard-rollup",
        "enterprise-dashboard-snapshot",
        "github-app-installation",
        "hosted-registry-ingest",
        "manifest",
        "multi-repo-artifacts",
        "policy-opa-input",
        "policy-pack",
        "post-release-smoke",
        "registry",
        "registry-diff",
        "registry-graph",
        "schema-audit",
        "schema-catalog",
        "slsa-readiness",
        "supply-chain-sbom",
    }.issubset(kinds)
    for kind in kinds:
        assert load_schema(kind)["$schema"] == "https://json-schema.org/draft/2020-12/schema"


def test_supply_chain_sbom_accepts_syft_components_without_version(tmp_path):
    sbom = tmp_path / "container-os-sbom.cdx.json"
    sbom.write_text(
        json.dumps(
            {
                "bomFormat": "CycloneDX",
                "specVersion": "1.6",
                "metadata": {
                    "component": {
                        "type": "container",
                        "name": "ghcr.io/bamboogap/skills-orchestrator",
                        "version": "v4.8.35",
                    }
                },
                "components": [
                    {
                        "type": "file",
                        "name": "/usr/local/bin/python",
                    }
                ],
            }
        ),
        encoding="utf-8",
    )

    assert validate_document("supply-chain-sbom", str(sbom)).valid is True


@pytest.mark.parametrize(
    ("kind", "filename"),
    [
        ("config", "config/skills.yaml"),
        ("check", "check.json"),
        ("ci-explainability", "ci-explainability.json"),
        ("conformance", "conformance.json"),
        ("container-provenance", "container-provenance.json"),
        ("doctor", "doctor.json"),
        ("evidence", "evidence/evidence-manifest.json"),
        ("manifest", "instruction-manifest.json"),
        ("multi-repo-artifacts", "multi-repo-artifacts.json"),
        ("policy-opa-input", "policy-opa-input.json"),
        ("policy-pack", "policy-pack.yaml"),
        ("post-release-smoke", "post-release-smoke.json"),
        ("registry", "skill-registry.json"),
        ("registry-diff", "registry-diff.json"),
        ("registry-graph", "registry-graph.json"),
        ("slsa-readiness", "slsa-readiness.json"),
        ("adapter-inspect", "adapter-inspect.json"),
        ("claude-skills-export", "claude-skills-export.json"),
        ("supply-chain-sbom", "package-sbom.cdx.json"),
        (
            "github-app-installation",
            "examples/commercial-handoff/installation.json",
        ),
        (
            "hosted-registry-ingest",
            "examples/commercial-handoff/registry-ingest.json",
        ),
        (
            "enterprise-dashboard-snapshot",
            "examples/commercial-handoff/dashboard-snapshot.json",
        ),
        (
            "enterprise-dashboard-rollup",
            "examples/commercial-handoff/dashboard-rollup.json",
        ),
        (
            "agent-handoff",
            "examples/agent-handoff/release-review-handoff.json",
        ),
        (
            "agent-runtime-image",
            "examples/agent-runtime-image/codex-worker-image.json",
        ),
    ],
)
def test_schema_validate_known_artifacts(tmp_path, monkeypatch, kind, filename):
    config = _schema_workspace(tmp_path)
    monkeypatch.chdir(tmp_path)
    _write_artifacts(config, tmp_path)
    runner = CliRunner()

    result = runner.invoke(
        cli,
        ["schema", "validate", "--kind", kind, "--input", str(tmp_path / filename)],
    )

    assert result.exit_code == 0
    assert "Schema valid" in result.output


def test_schema_validate_json_reports_paths_for_invalid_documents(tmp_path):
    bad_config = tmp_path / "bad-skills.yaml"
    bad_config.write_text('version: "2.0"\nskill_dirs: ../skills\nzones: []\n', encoding="utf-8")
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "schema",
            "validate",
            "--kind",
            "config",
            "--input",
            str(bad_config),
            "--format",
            "json",
        ],
    )

    assert result.exit_code == 1
    payload = json.loads(result.output)
    assert payload["valid"] is False
    assert any(error["path"] == "$.skill_dirs" for error in payload["errors"])
    assert any(error["path"] == "$.zones" for error in payload["errors"])


@pytest.mark.parametrize(
    "config_text",
    [
        """
skill_dirs:
  - ../skills
zones:
  - id: default
    name: Default
    load_policy: free
    rules: []
""",
        """
version: "2.0"
skill_dirs:
  - ../skills
""",
        """
version: "2.0"
skill_dirs:
  - ../skills
zones:
  - id: default
    load_policy: free
    rules: []
""",
    ],
)
def test_schema_validate_config_matches_parser_compatibility(tmp_path, config_text):
    skills_dir = tmp_path / "skills"
    skills_dir.mkdir()
    config = tmp_path / "config" / "skills.yaml"
    config.parent.mkdir()
    config.write_text(config_text, encoding="utf-8")
    runner = CliRunner()

    result = runner.invoke(
        cli,
        ["schema", "validate", "--kind", "config", "--input", str(config)],
    )

    assert result.exit_code == 0


def test_schema_list_json(tmp_path):
    runner = CliRunner()

    result = runner.invoke(cli, ["schema", "list", "--format", "json"])

    assert result.exit_code == 0
    payload = json.loads(result.output)
    assert payload["schema_version"] == "skills-orchestrator.schema-catalog.v1"
    schemas = {schema["kind"]: schema for schema in payload["schemas"]}
    assert "agent-handoff" in schemas
    assert "agent-runtime-image" in schemas
    assert "claude-skills-export" in schemas
    assert "config" in schemas
    assert schemas["config"]["stability"] == "stable"
    assert schemas["config"]["contract_id"] == "skills-orchestrator.config.v1"
    assert schemas["agent-handoff"]["stability"] == "preview"
    assert schemas["agent-handoff"]["contract_id"] == "skills-orchestrator.agent-handoff.v1"
    assert schemas["agent-runtime-image"]["stability"] == "preview"
    assert (
        schemas["agent-runtime-image"]["contract_id"]
        == "skills-orchestrator.agent-runtime-image.v1"
    )
    assert schemas["claude-skills-export"]["stability"] == "stable"
    assert (
        schemas["claude-skills-export"]["contract_id"]
        == "skills-orchestrator.claude-skills-export.v1"
    )
    assert schemas["enterprise-dashboard-rollup"]["stability"] == "preview"
    assert schemas["external-adoption-record"]["stability"] == "preview"
    assert (
        schemas["external-adoption-record"]["contract_id"]
        == "skills-orchestrator.external-adoption-record.v1"
    )
    catalog_file = tmp_path / "schema-catalog.json"
    catalog_file.write_text(result.output, encoding="utf-8")
    assert validate_document("schema-catalog", str(catalog_file)).valid is True


def test_schema_list_json_can_filter_stable_contracts(tmp_path):
    runner = CliRunner()

    result = runner.invoke(cli, ["schema", "list", "--format", "json", "--stability", "stable"])

    assert result.exit_code == 0
    payload = json.loads(result.output)
    assert payload["scope"]["stability"] == "stable"
    assert payload["schemas"]
    assert {schema["stability"] for schema in payload["schemas"]} == {"stable"}
    assert "agent-handoff" not in {schema["kind"] for schema in payload["schemas"]}
    catalog_file = tmp_path / "schema-catalog-stable.json"
    catalog_file.write_text(result.output, encoding="utf-8")
    assert validate_document("schema-catalog", str(catalog_file)).valid is True


def test_schema_audit_json_validates(tmp_path):
    runner = CliRunner()

    result = runner.invoke(cli, ["schema", "audit", "--format", "json"])

    assert result.exit_code == 0
    payload = json.loads(result.output)
    assert payload["schema_version"] == "skills-orchestrator.schema-audit.v1"
    assert payload["status"] == "pass"
    assert payload["summary"]["failed"] == 0
    audit_file = tmp_path / "schema-audit.json"
    audit_file.write_text(result.output, encoding="utf-8")
    assert validate_document("schema-audit", str(audit_file)).valid is True


def test_schema_audit_json_can_filter_stable_contracts(tmp_path):
    runner = CliRunner()

    result = runner.invoke(cli, ["schema", "audit", "--format", "json", "--stability", "stable"])

    assert result.exit_code == 0
    payload = json.loads(result.output)
    assert payload["scope"]["stability"] == "stable"
    assert payload["status"] == "pass"
    assert payload["summary"]["stable"] > 0
    assert payload["summary"]["preview"] == 0
    assert not any(check["kind"] == "agent-handoff" for check in payload["checks"])
    audit_file = tmp_path / "schema-audit-stable.json"
    audit_file.write_text(result.output, encoding="utf-8")
    assert validate_document("schema-audit", str(audit_file)).valid is True


def test_schema_audit_json_can_filter_preview_contracts(tmp_path):
    runner = CliRunner()

    result = runner.invoke(cli, ["schema", "audit", "--format", "json", "--stability", "preview"])

    assert result.exit_code == 0
    payload = json.loads(result.output)
    assert payload["scope"]["stability"] == "preview"
    assert payload["status"] == "pass"
    assert payload["summary"]["stable"] == 0
    assert payload["summary"]["preview"] > 0
    assert any(check["kind"] == "agent-handoff" for check in payload["checks"])
    assert any(check["kind"] == "external-adoption-record" for check in payload["checks"])
    audit_file = tmp_path / "schema-audit-preview.json"
    audit_file.write_text(result.output, encoding="utf-8")
    assert validate_document("schema-audit", str(audit_file)).valid is True


def test_schema_audit_text_passes():
    runner = CliRunner()

    result = runner.invoke(cli, ["schema", "audit"])

    assert result.exit_code == 0
    assert "Schema audit: pass" in result.output
    assert "Scope: all" in result.output


def test_hosted_registry_ingest_rejects_unsafe_artifact_paths(tmp_path):
    payload = {
        "schema_version": "skills-orchestrator.hosted-registry-ingest.v1",
        "snapshot": {"id": "s1", "created_at": "2026-06-21T00:00:00Z"},
        "source": {"repository": "org/repo", "commit": "abc"},
        "artifacts": {
            "registry": "../secret.json",
            "evidence_manifest": "https://example.test/evidence.json",
        },
    }
    input_file = tmp_path / "ingest.json"
    input_file.write_text(json.dumps(payload), encoding="utf-8")
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "schema",
            "validate",
            "--kind",
            "hosted-registry-ingest",
            "--input",
            str(input_file),
            "--format",
            "json",
        ],
    )

    assert result.exit_code == 1
    result_payload = json.loads(result.output)
    assert any(error["path"].startswith("$.artifacts") for error in result_payload["errors"])


def test_github_app_installation_rejects_overbroad_permissions(tmp_path):
    payload = {
        "schema_version": "skills-orchestrator.github-app-installation.v1",
        "installation": {"id": 1, "account": "org"},
        "repository": {"full_name": "org/repo", "default_branch": "main"},
        "permissions": {
            "contents": "write",
            "metadata": "read",
            "pull_requests": "write",
            "administration": "write",
        },
        "events": ["pull_request", "repository"],
    }
    input_file = tmp_path / "installation.json"
    input_file.write_text(json.dumps(payload), encoding="utf-8")
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "schema",
            "validate",
            "--kind",
            "github-app-installation",
            "--input",
            str(input_file),
            "--format",
            "json",
        ],
    )

    assert result.exit_code == 1
    result_payload = json.loads(result.output)
    assert any(error["path"].startswith("$.permissions") for error in result_payload["errors"])


def test_external_adoption_record_example_validates():
    input_file = (
        Path(__file__).resolve().parents[1]
        / "examples"
        / "external-adoption-record"
        / "advisory-adoption-record.json"
    )

    result = validate_document("external-adoption-record", str(input_file))

    assert result.valid is True


def test_external_adoption_record_rejects_unsafe_artifact_path(tmp_path):
    payload = {
        "schema_version": "skills-orchestrator.external-adoption-record.v1",
        "adoption": {
            "repository": "org/repo",
            "adoption_owner": "platform-team",
            "started_at": "2026-06-28T00:00:00Z",
            "skillops_version": "v4.8.35",
            "ci_system": "github-actions",
        },
        "gate": {"mode": "advisory", "policy_pack": "builtin/team-standard"},
        "artifacts": {
            "check_json": {"status": "present", "path": "../check.json"},
            "sarif": {"status": "present", "path": "artifacts/skills-orchestrator.sarif"},
            "registry_diff": {"status": "present", "path": "artifacts/registry-diff.md"},
            "evidence_manifest": {
                "status": "present",
                "path": "artifacts/evidence/evidence-manifest.json",
            },
            "conformance_report": {
                "status": "present",
                "path": "artifacts/conformance.json",
            },
        },
        "authorization": {
            "tier": "private-technical-adoption",
            "decided_at": "2026-06-28T00:15:00Z",
            "approved_by": "platform-team",
        },
        "promotion": {
            "decision": "stay-advisory",
            "decided_at": "2026-06-28T00:30:00Z",
        },
        "public_listing": {"status": "not-requested"},
    }
    input_file = tmp_path / "adoption-record.json"
    input_file.write_text(json.dumps(payload), encoding="utf-8")
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "schema",
            "validate",
            "--kind",
            "external-adoption-record",
            "--input",
            str(input_file),
            "--format",
            "json",
        ],
    )

    assert result.exit_code == 1
    result_payload = json.loads(result.output)
    assert any(
        error["path"].startswith("$.artifacts.check_json.path")
        for error in result_payload["errors"]
    )


def test_external_adoption_record_rejects_public_listing_without_public_authorization(tmp_path):
    payload = {
        "schema_version": "skills-orchestrator.external-adoption-record.v1",
        "adoption": {
            "repository": "org/repo",
            "adoption_owner": "platform-team",
            "started_at": "2026-06-28T00:00:00Z",
            "skillops_version": "v4.8.35",
            "ci_system": "github-actions",
        },
        "gate": {"mode": "advisory", "policy_pack": "builtin/team-standard"},
        "artifacts": {
            "check_json": {"status": "present", "path": "artifacts/check.json"},
            "sarif": {"status": "present", "path": "artifacts/skills-orchestrator.sarif"},
            "registry_diff": {"status": "present", "path": "artifacts/registry-diff.md"},
            "evidence_manifest": {
                "status": "present",
                "path": "artifacts/evidence/evidence-manifest.json",
            },
            "conformance_report": {
                "status": "present",
                "path": "artifacts/conformance.json",
            },
        },
        "authorization": {
            "tier": "private-technical-adoption",
            "decided_at": "2026-06-28T00:15:00Z",
            "approved_by": "platform-team",
        },
        "promotion": {
            "decision": "promote-warning",
            "decided_at": "2026-06-28T00:30:00Z",
        },
        "public_listing": {
            "status": "approved",
            "approved_by": "repo-maintainer",
            "approved_at": "2026-06-28T00:35:00Z",
        },
    }
    input_file = tmp_path / "adoption-record.json"
    input_file.write_text(json.dumps(payload), encoding="utf-8")
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "schema",
            "validate",
            "--kind",
            "external-adoption-record",
            "--input",
            str(input_file),
            "--format",
            "json",
        ],
    )

    assert result.exit_code == 1
    result_payload = json.loads(result.output)
    assert any(error["path"].startswith("$") for error in result_payload["errors"])


@pytest.mark.parametrize("tier", ["public-adopter-reference", "public-case-study"])
def test_external_adoption_record_accepts_public_listing_with_public_authorization(tmp_path, tier):
    payload = {
        "schema_version": "skills-orchestrator.external-adoption-record.v1",
        "adoption": {
            "repository": "org/repo",
            "adoption_owner": "platform-team",
            "started_at": "2026-06-28T00:00:00Z",
            "skillops_version": "v4.8.35",
            "ci_system": "github-actions",
        },
        "gate": {"mode": "advisory", "policy_pack": "builtin/team-standard"},
        "artifacts": {
            "check_json": {"status": "present", "path": "artifacts/check.json"},
            "sarif": {"status": "present", "path": "artifacts/skills-orchestrator.sarif"},
            "registry_diff": {"status": "present", "path": "artifacts/registry-diff.md"},
            "evidence_manifest": {
                "status": "present",
                "path": "artifacts/evidence/evidence-manifest.json",
            },
            "conformance_report": {
                "status": "present",
                "path": "artifacts/conformance.json",
            },
        },
        "authorization": {
            "tier": tier,
            "decided_at": "2026-06-28T00:15:00Z",
            "approved_by": "repo-maintainer",
        },
        "promotion": {
            "decision": "promote-warning",
            "decided_at": "2026-06-28T00:30:00Z",
        },
        "public_listing": {
            "status": "approved",
            "approved_by": "repo-maintainer",
            "approved_at": "2026-06-28T00:35:00Z",
        },
    }
    input_file = tmp_path / "adoption-record.json"
    input_file.write_text(json.dumps(payload), encoding="utf-8")

    result = validate_document("external-adoption-record", str(input_file))

    assert result.valid is True


def test_agent_handoff_rejects_privileged_worker_without_human_approval(tmp_path):
    input_file = (
        Path(__file__).resolve().parents[1]
        / "examples"
        / "agent-handoff"
        / "invalid-privileged-worker.json"
    )
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "schema",
            "validate",
            "--kind",
            "agent-handoff",
            "--input",
            str(input_file),
            "--format",
            "json",
        ],
    )

    assert result.exit_code == 1
    result_payload = json.loads(result.output)
    assert any(
        error["path"] == "$.workers[0].requires_human_approval"
        for error in result_payload["errors"]
    )


def _write_artifacts(config, root):
    cfg = Parser(str(config)).parse()
    resolved = Resolver(cfg).resolve()
    check_report = run_check(str(config), policy_packs=["builtin/team-standard"])
    (root / "check.json").write_text(format_diagnostics_json(check_report), encoding="utf-8")
    (root / "ci-explainability.json").write_text(
        format_ci_explainability_json(
            build_ci_explainability(check_report, config_path=str(config))
        ),
        encoding="utf-8",
    )
    conformance = run_conformance(str(config), project_root=str(root))
    (root / "conformance.json").write_text(
        json.dumps(conformance, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    manifest = build_instruction_manifest(str(config), cfg, resolved)
    (root / "instruction-manifest.json").write_text(
        format_instruction_manifest_json(manifest), encoding="utf-8"
    )
    opa_input = build_opa_input(cfg, resolved)
    (root / "policy-opa-input.json").write_text(
        json.dumps(opa_input, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    (root / "policy-pack.yaml").write_text(
        """
schema_version: skills-orchestrator.policy-pack.v1
id: org/schema-fixture
rules:
  - id: require-owner
    severity: warning
    required_fields: [owner]
""",
        encoding="utf-8",
    )
    (root / "post-release-smoke.json").write_text(
        json.dumps(
            {
                "schema_version": "skills-orchestrator.post-release-smoke.v1",
                "status": "pass",
                "summary": {"passed": 1, "failed": 0},
                "checks": [
                    {
                        "name": "github-release-tag",
                        "ok": True,
                        "message": "tag='v0.0.0', expected='v0.0.0'",
                    }
                ],
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    doctor_result = CliRunner().invoke(cli, ["doctor", "--config", str(config), "--format", "json"])
    assert doctor_result.exit_code == 0
    (root / "doctor.json").write_text(doctor_result.output, encoding="utf-8")
    registry = build_registry([str(config)])
    (root / "skill-registry.json").write_text(
        json.dumps(registry, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    registry_diff = diff_registries(registry, registry)
    (root / "registry-diff.json").write_text(
        json.dumps(registry_diff, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    registry_graph = build_registry_graph(registry)
    (root / "registry-graph.json").write_text(
        json.dumps(registry_graph, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    export_evidence_bundle(
        str(config),
        str(root / "evidence"),
        policy_packs=["builtin/team-standard"],
    )
    index_result = CliRunner().invoke(
        cli,
        [
            "evidence",
            "index",
            "--manifest",
            f"schema-repo={root / 'evidence' / 'evidence-manifest.json'}",
            "--scope-name",
            "schema-fixture",
            "--output",
            str(root / "multi-repo-artifacts.json"),
        ],
    )
    assert index_result.exit_code == 0
    (root / "adapter-inspect.json").write_text(
        json.dumps(inspect_adapters(root), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    claude_export = export_claude_skill_bundles(
        str(config),
        root / ".claude" / "skills",
        force=True,
    )
    (root / "claude-skills-export.json").write_text(
        json.dumps(claude_export, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (root / "package-sbom.cdx.json").write_text(
        format_sbom_json(build_python_package_sbom(include_dependencies=False)),
        encoding="utf-8",
    )
    (root / "slsa-readiness.json").write_text(
        format_slsa_readiness_json(
            build_slsa_readiness(
                release_version="v0.0.0",
                digest="sha256:" + ("b" * 64),
            )
        ),
        encoding="utf-8",
    )
    runner = CliRunner()
    digest = "sha256:" + ("a" * 64)
    container_result = runner.invoke(
        cli,
        [
            "supply-chain",
            "container-release",
            "--image",
            "ghcr.io/bamboogap/skills-orchestrator",
            "--tag",
            "v0.0.0",
            "--digest",
            digest,
            "--repository",
            "BambooGap/skills-orchestrator",
            "--commit",
            "abc123",
            "--sbom-output",
            str(root / "container-sbom.cdx.json"),
            "--provenance-output",
            str(root / "container-provenance.json"),
            "--no-dependencies",
        ],
    )
    assert container_result.exit_code == 0
    handoff = root / "examples" / "commercial-handoff"
    handoff.mkdir(parents=True)
    repo_examples = Path(__file__).resolve().parents[1] / "examples" / "commercial-handoff"
    for name in (
        "installation.json",
        "registry-ingest.json",
        "dashboard-snapshot.json",
        "dashboard-rollup.json",
    ):
        (handoff / name).write_text(
            (repo_examples / name).read_text(encoding="utf-8"),
            encoding="utf-8",
        )
    agent_handoff = root / "examples" / "agent-handoff"
    agent_handoff.mkdir(parents=True)
    repo_handoff_examples = Path(__file__).resolve().parents[1] / "examples" / "agent-handoff"
    (agent_handoff / "release-review-handoff.json").write_text(
        (repo_handoff_examples / "release-review-handoff.json").read_text(encoding="utf-8"),
        encoding="utf-8",
    )
    agent_runtime = root / "examples" / "agent-runtime-image"
    agent_runtime.mkdir(parents=True)
    repo_runtime_examples = Path(__file__).resolve().parents[1] / "examples" / "agent-runtime-image"
    (agent_runtime / "codex-worker-image.json").write_text(
        (repo_runtime_examples / "codex-worker-image.json").read_text(encoding="utf-8"),
        encoding="utf-8",
    )
