"""集成测试 - 端到端场景验证"""

import os
import tempfile
from pathlib import Path

import pytest

from src.compiler.parser import Parser
from src.compiler.resolver import Resolver
from src.compiler.compressor import Compressor
from src.enforcer import Enforcer
from src.models import Zone, Rule, SkillMeta, Config, Manifest


def _make_config_with_skills(skills, zones=None):
    """创建测试用 Config"""
    default_zone = Zone(id="default", name="默认", priority=0, load_policy="free")
    all_zones = zones if zones else [default_zone]
    return Config(zones=all_zones, default_zone=default_zone, skills=skills, combos=[])


def test_build_generates_valid_agents_md(tmp_path):
    """build 输出文件存在且格式正确"""
    # 创建测试 skill 文件
    skills_dir = tmp_path / "skills"
    skills_dir.mkdir()
    
    skill_file = skills_dir / "test-skill.md"
    skill_file.write_text("# Test Skill\n\n测试内容", encoding="utf-8")
    
    # 创建配置
    skills = [
        SkillMeta(
            id="test-skill",
            name="测试技能",
            path=str(skill_file),
            summary="测试用技能",
            tags=["test"],
            load_policy="free",
            priority=100,
            zones=["default"],
            conflict_with=[],
        )
    ]
    
    config = _make_config_with_skills(skills)
    
    # 解析和生成
    resolver = Resolver(config)
    resolved = resolver.resolve()
    
    compressor = Compressor(resolved)
    manifest = compressor.compress()
    agents_md = compressor.generate_agents_md(manifest, resolved.active_zone)
    
    # 验证输出
    assert "## Required Skills" in agents_md
    assert "## Available Skills" in agents_md
    assert "Generated by Skills Orchestrator" in agents_md
    assert "测试技能" in agents_md
    assert "测试用技能" in agents_md


def test_build_with_zone_flag(tmp_path):
    """--zone 参数正确切换 Zone"""
    # 创建测试 skill 文件
    skills_dir = tmp_path / "skills"
    skills_dir.mkdir()
    
    enterprise_skill = skills_dir / "enterprise-skill.md"
    enterprise_skill.write_text("# Enterprise Skill\n\n企业专属内容", encoding="utf-8")
    
    default_skill = skills_dir / "default-skill.md"
    default_skill.write_text("# Default Skill\n\n默认内容", encoding="utf-8")
    
    # 创建 Zone
    enterprise_zone = Zone(
        id="enterprise",
        name="企业区",
        priority=200,
        load_policy="require",
        rules=[],
    )
    default_zone = Zone(
        id="default",
        name="默认区",
        priority=0,
        load_policy="free",
        rules=[],
    )
    
    # 创建 skills
    skills = [
        SkillMeta(
            id="enterprise-skill",
            name="企业技能",
            path=str(enterprise_skill),
            summary="企业专属",
            tags=["enterprise"],
            load_policy="require",
            priority=200,
            zones=["enterprise"],
            conflict_with=[],
        ),
        SkillMeta(
            id="default-skill",
            name="默认技能",
            path=str(default_skill),
            summary="默认可用",
            tags=["default"],
            load_policy="free",
            priority=100,
            zones=["default"],
            conflict_with=[],
        ),
    ]
    
    config = Config(
        zones=[enterprise_zone, default_zone],
        default_zone=default_zone,
        skills=skills,
        combos=[],
    )
    
    # 使用 enterprise zone
    resolver = Resolver(config)
    resolved = resolver.resolve(enterprise_zone)
    
    compressor = Compressor(resolved)
    manifest = compressor.compress()
    agents_md = compressor.generate_agents_md(manifest, enterprise_zone)
    
    # 验证 Zone header
    assert "Zone: enterprise" in agents_md
    # 验证企业 skill 被加载（require skill 显示完整内容）
    assert "Enterprise Skill" in agents_md
    assert "企业专属内容" in agents_md


def test_validate_catches_require_conflict():
    """validate 能检出 require 互冲突"""
    # 创建两个互相冲突的 require skill
    skill1 = SkillMeta(
        id="skill-a",
        name="技能A",
        path="/fake/skill-a.md",
        summary="技能A",
        tags=["a"],
        load_policy="require",
        priority=100,
        zones=["default"],
        conflict_with=["skill-b"],
    )
    
    skill2 = SkillMeta(
        id="skill-b",
        name="技能B",
        path="/fake/skill-b.md",
        summary="技能B",
        tags=["b"],
        load_policy="require",
        priority=100,
        zones=["default"],
        conflict_with=["skill-a"],
    )
    
    config = _make_config_with_skills([skill1, skill2])
    
    resolver = Resolver(config)
    
    # 应该抛出 ValueError
    with pytest.raises(ValueError, match="互相冲突"):
        resolver.resolve()


def test_build_with_actual_skill_files():
    """使用真实 skill 文件（skill_dirs 格式）测试完整流程"""
    project_root = Path(__file__).parent.parent
    config_path = project_root / "config" / "skills.yaml"
    if not config_path.exists():
        pytest.skip("配置文件不存在")

    # skill_dirs 使用绝对路径，不需要 SKILLS_ROOT
    parser = Parser(str(config_path))
    config = parser.parse()

    assert len(config.skills) >= 10, f"应发现至少 10 个 skill，实际: {len(config.skills)}"

    resolver = Resolver(config)
    resolved = resolver.resolve()

    compressor = Compressor(resolved)
    manifest = compressor.compress()
    agents_md = compressor.generate_agents_md(manifest, resolved.active_zone)

    assert "## Required Skills" in agents_md
    assert "## Available Skills" in agents_md


def test_auto_discovery_from_dirs(tmp_path):
    """skill_dirs 自动发现：从 frontmatter 正确解析 skill 元数据"""
    # 创建子目录结构
    git_dir = tmp_path / "skills" / "git"
    git_dir.mkdir(parents=True)
    review_dir = tmp_path / "skills" / "review"
    review_dir.mkdir(parents=True)

    (git_dir / "my-git-skill.md").write_text(
        "---\n"
        "id: my-git-skill\n"
        "name: My Git Skill\n"
        "summary: git skill summary\n"
        "tags: [git]\n"
        "load_policy: free\n"
        "priority: 80\n"
        "zones: [default]\n"
        "conflict_with: []\n"
        "---\n\n# My Git Skill\n",
        encoding="utf-8",
    )
    (review_dir / "my-review-skill.md").write_text(
        "---\n"
        "id: my-review-skill\n"
        "name: My Review Skill\n"
        "summary: review skill summary\n"
        "tags: [review]\n"
        "load_policy: require\n"
        "priority: 150\n"
        "zones: [default]\n"
        "conflict_with: []\n"
        "---\n\n# My Review Skill\n",
        encoding="utf-8",
    )

    # 创建使用 skill_dirs 的 skills.yaml
    config_file = tmp_path / "skills.yaml"
    config_file.write_text(
        "version: '2.0'\n"
        "skill_dirs:\n"
        "  - ./skills\n"
        "zones:\n"
        "  - id: default\n"
        "    name: 默认区\n"
        "    load_policy: free\n"
        "    priority: 0\n"
        "    rules: []\n"
        "overrides: []\n"
        "combos: []\n",
        encoding="utf-8",
    )

    parser = Parser(str(config_file))
    config = parser.parse()

    assert len(config.skills) == 2
    ids = {s.id for s in config.skills}
    assert "my-git-skill" in ids
    assert "my-review-skill" in ids

    review = next(s for s in config.skills if s.id == "my-review-skill")
    assert review.load_policy == "require"
    assert review.priority == 150
    assert "review" in review.tags


def test_auto_discovery_overrides(tmp_path):
    """overrides 段正确覆盖 frontmatter 里的字段"""
    skills_dir = tmp_path / "skills"
    skills_dir.mkdir()

    (skills_dir / "some-skill.md").write_text(
        "---\n"
        "id: some-skill\n"
        "name: Some Skill\n"
        "summary: original summary\n"
        "tags: [tag1]\n"
        "load_policy: free\n"
        "priority: 50\n"
        "zones: [default]\n"
        "conflict_with: []\n"
        "---\n\n# Some Skill\n",
        encoding="utf-8",
    )

    config_file = tmp_path / "skills.yaml"
    config_file.write_text(
        "version: '2.0'\n"
        "skill_dirs:\n"
        "  - ./skills\n"
        "zones:\n"
        "  - id: default\n"
        "    name: 默认区\n"
        "    load_policy: free\n"
        "    priority: 0\n"
        "    rules: []\n"
        "overrides:\n"
        "  - id: some-skill\n"
        "    load_policy: require\n"
        "    priority: 200\n"
        "combos: []\n",
        encoding="utf-8",
    )

    parser = Parser(str(config_file))
    config = parser.parse()

    skill = config.skills[0]
    assert skill.id == "some-skill"
    # overrides 覆盖了 frontmatter
    assert skill.load_policy == "require"
    assert skill.priority == 200
    # 未覆盖的字段保持 frontmatter 原值
    assert skill.summary == "original summary"
    assert "tag1" in skill.tags


def test_auto_discovery_no_frontmatter(tmp_path):
    """无 frontmatter 的 .md 文件：从文件名推断 id，从内容推断 summary"""
    skills_dir = tmp_path / "skills"
    skills_dir.mkdir()

    (skills_dir / "plain-skill.md").write_text(
        "# Plain Skill Title\n\nThis is the skill description paragraph.\n",
        encoding="utf-8",
    )

    config_file = tmp_path / "skills.yaml"
    config_file.write_text(
        "version: '2.0'\n"
        "skill_dirs:\n  - ./skills\n"
        "zones:\n  - id: default\n    name: 默认区\n    load_policy: free\n    priority: 0\n    rules: []\n"
        "overrides: []\ncombos: []\n",
        encoding="utf-8",
    )

    parser = Parser(str(config_file))
    config = parser.parse()

    assert len(config.skills) == 1
    skill = config.skills[0]
    assert skill.id == "plain-skill"          # 从文件名推断
    assert skill.load_policy == "free"        # 默认值


def test_enforcer_detect_zone_with_marker_file(tmp_path):
    """Enforcer 正确检测 marker 文件"""
    # 创建 marker 文件
    (tmp_path / ".enterprise").write_text("", encoding="utf-8")
    
    enterprise_zone = Zone(
        id="enterprise",
        name="企业区",
        priority=200,
        load_policy="require",
        rules=[Rule(git_contains=".enterprise")],
    )
    default_zone = Zone(
        id="default",
        name="默认区",
        priority=0,
        load_policy="free",
        rules=[],
    )
    
    config = Config(
        zones=[enterprise_zone, default_zone],
        default_zone=default_zone,
        skills=[],
        combos=[],
    )
    
    enforcer = Enforcer(config, Manifest())
    detected = enforcer.detect_zone(str(tmp_path))
    
    assert detected.id == "enterprise"
