import json
from pathlib import Path

import pytest
from click.testing import CliRunner

from skills_orchestrator.adapters import inspect_adapters
from skills_orchestrator.checker import run_check
from skills_orchestrator.compiler import Parser, Resolver
from skills_orchestrator.compiler.instruction_manifest import build_instruction_manifest
from skills_orchestrator.evidence import export_evidence_bundle
from skills_orchestrator.formatters import format_diagnostics_json
from skills_orchestrator.formatters.manifest import format_instruction_manifest_json
from skills_orchestrator.main import cli
from skills_orchestrator.org_registry import build_registry, diff_registries
from skills_orchestrator.policy import build_opa_input
from skills_orchestrator.schema_validation import list_schema_descriptors, load_schema
from skills_orchestrator.supply_chain import build_python_package_sbom, format_sbom_json


def _schema_workspace(tmp_path):
    skills_dir = tmp_path / "skills"
    skills_dir.mkdir()
    (skills_dir / "team.md").write_text(
        "---\n"
        "id: team-skill\n"
        "name: Team Skill\n"
        "summary: Team governed skill\n"
        "load_policy: require\n"
        "priority: 80\n"
        "owner: platform-team\n"
        "source: internal://skills/team-skill\n"
        "version: 1.0.0\n"
        "lifecycle: active\n"
        "approvers: [platform-team]\n"
        "---\n"
        "# Team Skill\n",
        encoding="utf-8",
    )
    config_dir = tmp_path / "config"
    config_dir.mkdir()
    config = config_dir / "skills.yaml"
    config.write_text(
        """
version: "2.0"
skill_dirs:
  - ../skills
zones:
  - id: default
    name: Default
    load_policy: free
    priority: 0
    rules: []
overrides: []
combos: []
""",
        encoding="utf-8",
    )
    (tmp_path / "AGENTS.md").write_text(
        "<!-- Generated by Skills Orchestrator v2.5.1 | Zone: default -->\n",
        encoding="utf-8",
    )
    (tmp_path / ".github" / "workflows").mkdir(parents=True)
    (tmp_path / ".github" / "workflows" / "ci.yml").write_text(
        "name: ci\njobs:\n  skillops:\n    steps:\n      - uses: BambooGap/skills-orchestrator@v3\n",
        encoding="utf-8",
    )
    (tmp_path / "action.yml").write_text("name: action\n", encoding="utf-8")
    (tmp_path / "Dockerfile").write_text("FROM python:3.12-slim\n", encoding="utf-8")
    return config


def test_schema_resources_are_packaged_and_loadable():
    kinds = {descriptor.kind for descriptor in list_schema_descriptors()}

    assert {
        "adapter-inspect",
        "check",
        "config",
        "doctor",
        "evidence",
        "enterprise-dashboard-snapshot",
        "github-app-installation",
        "hosted-registry-ingest",
        "manifest",
        "policy-opa-input",
        "registry",
        "registry-diff",
        "supply-chain-sbom",
    }.issubset(kinds)
    for kind in kinds:
        assert load_schema(kind)["$schema"] == "https://json-schema.org/draft/2020-12/schema"


@pytest.mark.parametrize(
    ("kind", "filename"),
    [
        ("config", "config/skills.yaml"),
        ("check", "check.json"),
        ("doctor", "doctor.json"),
        ("evidence", "evidence/evidence-manifest.json"),
        ("manifest", "instruction-manifest.json"),
        ("policy-opa-input", "policy-opa-input.json"),
        ("registry", "skill-registry.json"),
        ("registry-diff", "registry-diff.json"),
        ("adapter-inspect", "adapter-inspect.json"),
        ("supply-chain-sbom", "package-sbom.cdx.json"),
        (
            "github-app-installation",
            "examples/commercial-handoff/installation.json",
        ),
        (
            "hosted-registry-ingest",
            "examples/commercial-handoff/registry-ingest.json",
        ),
        (
            "enterprise-dashboard-snapshot",
            "examples/commercial-handoff/dashboard-snapshot.json",
        ),
    ],
)
def test_schema_validate_known_artifacts(tmp_path, monkeypatch, kind, filename):
    config = _schema_workspace(tmp_path)
    monkeypatch.chdir(tmp_path)
    _write_artifacts(config, tmp_path)
    runner = CliRunner()

    result = runner.invoke(
        cli,
        ["schema", "validate", "--kind", kind, "--input", str(tmp_path / filename)],
    )

    assert result.exit_code == 0
    assert "Schema valid" in result.output


def test_schema_validate_json_reports_paths_for_invalid_documents(tmp_path):
    bad_config = tmp_path / "bad-skills.yaml"
    bad_config.write_text('version: "2.0"\nskill_dirs: ../skills\nzones: []\n', encoding="utf-8")
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "schema",
            "validate",
            "--kind",
            "config",
            "--input",
            str(bad_config),
            "--format",
            "json",
        ],
    )

    assert result.exit_code == 1
    payload = json.loads(result.output)
    assert payload["valid"] is False
    assert any(error["path"] == "$.skill_dirs" for error in payload["errors"])
    assert any(error["path"] == "$.zones" for error in payload["errors"])


@pytest.mark.parametrize(
    "config_text",
    [
        """
skill_dirs:
  - ../skills
zones:
  - id: default
    name: Default
    load_policy: free
    rules: []
""",
        """
version: "2.0"
skill_dirs:
  - ../skills
""",
        """
version: "2.0"
skill_dirs:
  - ../skills
zones:
  - id: default
    load_policy: free
    rules: []
""",
    ],
)
def test_schema_validate_config_matches_parser_compatibility(tmp_path, config_text):
    skills_dir = tmp_path / "skills"
    skills_dir.mkdir()
    config = tmp_path / "config" / "skills.yaml"
    config.parent.mkdir()
    config.write_text(config_text, encoding="utf-8")
    runner = CliRunner()

    result = runner.invoke(
        cli,
        ["schema", "validate", "--kind", "config", "--input", str(config)],
    )

    assert result.exit_code == 0


def test_schema_list_json():
    runner = CliRunner()

    result = runner.invoke(cli, ["schema", "list", "--format", "json"])

    assert result.exit_code == 0
    payload = json.loads(result.output)
    assert payload["schema_version"] == "skills-orchestrator.schema-catalog.v1"
    assert "config" in {schema["kind"] for schema in payload["schemas"]}


def test_hosted_registry_ingest_rejects_unsafe_artifact_paths(tmp_path):
    payload = {
        "schema_version": "skills-orchestrator.hosted-registry-ingest.v1",
        "snapshot": {"id": "s1", "created_at": "2026-06-21T00:00:00Z"},
        "source": {"repository": "org/repo", "commit": "abc"},
        "artifacts": {
            "registry": "../secret.json",
            "evidence_manifest": "https://example.test/evidence.json",
        },
    }
    input_file = tmp_path / "ingest.json"
    input_file.write_text(json.dumps(payload), encoding="utf-8")
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "schema",
            "validate",
            "--kind",
            "hosted-registry-ingest",
            "--input",
            str(input_file),
            "--format",
            "json",
        ],
    )

    assert result.exit_code == 1
    result_payload = json.loads(result.output)
    assert any(error["path"].startswith("$.artifacts") for error in result_payload["errors"])


def test_github_app_installation_rejects_overbroad_permissions(tmp_path):
    payload = {
        "schema_version": "skills-orchestrator.github-app-installation.v1",
        "installation": {"id": 1, "account": "org"},
        "repository": {"full_name": "org/repo", "default_branch": "main"},
        "permissions": {
            "contents": "write",
            "metadata": "read",
            "pull_requests": "write",
            "administration": "write",
        },
        "events": ["pull_request", "repository"],
    }
    input_file = tmp_path / "installation.json"
    input_file.write_text(json.dumps(payload), encoding="utf-8")
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "schema",
            "validate",
            "--kind",
            "github-app-installation",
            "--input",
            str(input_file),
            "--format",
            "json",
        ],
    )

    assert result.exit_code == 1
    result_payload = json.loads(result.output)
    assert any(error["path"].startswith("$.permissions") for error in result_payload["errors"])


def _write_artifacts(config, root):
    cfg = Parser(str(config)).parse()
    resolved = Resolver(cfg).resolve()
    check_report = run_check(str(config), policy_packs=["builtin/team-standard"])
    (root / "check.json").write_text(format_diagnostics_json(check_report), encoding="utf-8")
    manifest = build_instruction_manifest(str(config), cfg, resolved)
    (root / "instruction-manifest.json").write_text(
        format_instruction_manifest_json(manifest), encoding="utf-8"
    )
    opa_input = build_opa_input(cfg, resolved)
    (root / "policy-opa-input.json").write_text(
        json.dumps(opa_input, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    doctor_result = CliRunner().invoke(cli, ["doctor", "--config", str(config), "--format", "json"])
    assert doctor_result.exit_code == 0
    (root / "doctor.json").write_text(doctor_result.output, encoding="utf-8")
    registry = build_registry([str(config)])
    (root / "skill-registry.json").write_text(
        json.dumps(registry, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    registry_diff = diff_registries(registry, registry)
    (root / "registry-diff.json").write_text(
        json.dumps(registry_diff, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    export_evidence_bundle(
        str(config),
        str(root / "evidence"),
        policy_packs=["builtin/team-standard"],
    )
    (root / "adapter-inspect.json").write_text(
        json.dumps(inspect_adapters(root), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (root / "package-sbom.cdx.json").write_text(
        format_sbom_json(build_python_package_sbom(include_dependencies=False)),
        encoding="utf-8",
    )
    handoff = root / "examples" / "commercial-handoff"
    handoff.mkdir(parents=True)
    repo_examples = Path(__file__).resolve().parents[1] / "examples" / "commercial-handoff"
    for name in ("installation.json", "registry-ingest.json", "dashboard-snapshot.json"):
        (handoff / name).write_text(
            (repo_examples / name).read_text(encoding="utf-8"),
            encoding="utf-8",
        )
