from pathlib import Path
import os

from skills_orchestrator.compiler.parser import Parser
from skills_orchestrator.compiler.resolver import Resolver
from skills_orchestrator.compiler.compressor import Compressor
from skills_orchestrator.models import Manifest


def test_compressor_generates_manifest():
    """测试 Compressor 生成 Manifest"""
    # 设置测试环境变量
    test_skills_dir = Path(__file__).parent.parent / "test-skills"
    os.environ["SKILLS_ROOT"] = str(test_skills_dir)

    # 解析配置
    config_path = Path(__file__).parent.parent / "config" / "test-skills.yaml"
    parser = Parser(str(config_path))
    cfg = parser.parse()

    # 解决冲突
    resolver = Resolver(cfg)
    resolved = resolver.resolve()

    # 压缩生成
    compressor = Compressor(resolved)
    manifest = compressor.compress()

    # 验证 Manifest
    assert isinstance(manifest, Manifest)
    assert len(manifest.blocked_list) >= 0


def test_compressor_agents_md_format():
    """测试 AGENTS.md 格式"""
    test_skills_dir = Path(__file__).parent.parent / "test-skills"
    os.environ["SKILLS_ROOT"] = str(test_skills_dir)

    config_path = Path(__file__).parent.parent / "config" / "test-skills.yaml"
    parser = Parser(str(config_path))
    cfg = parser.parse()

    resolver = Resolver(cfg)
    resolved = resolver.resolve()

    compressor = Compressor(resolved)
    manifest = compressor.compress()
    agents_md = compressor.generate_agents_md(manifest, resolved.active_zone)

    # 验证格式
    assert "## Required Skills" in agents_md
    assert "## Available Skills" in agents_md
    assert "## Runtime Skill Loading" in agents_md
    assert "prepare_context" in agents_md
    assert "Generated by Skills Orchestrator" in agents_md


def test_blocked_skills_not_in_output():
    """测试 blocked skills 不出现在输出中"""
    test_skills_dir = Path(__file__).parent.parent / "test-skills"
    os.environ["SKILLS_ROOT"] = str(test_skills_dir)

    config_path = Path(__file__).parent.parent / "config" / "test-skills.yaml"
    parser = Parser(str(config_path))
    cfg = parser.parse()

    resolver = Resolver(cfg)
    resolved = resolver.resolve()

    compressor = Compressor(resolved)
    manifest = compressor.compress()
    agents_md = compressor.generate_agents_md(manifest, resolved.active_zone)

    # blocked skills 不应该出现在输出中
    for blocked_id in manifest.blocked_list:
        assert blocked_id not in agents_md or "blocked" not in agents_md.lower()
