"""Helpers for GitHub PR-facing text artifacts.

This module deliberately avoids GitHub API calls. The CLI can generate stable
comment bodies, while GitHub Actions or external apps own authentication and
comment update behavior.
"""

from __future__ import annotations

from pathlib import Path

REGISTRY_DIFF_COMMENT_MARKER = "<!-- skills-orchestrator:registry-diff-comment:v1 -->"
DEFAULT_MAX_COMMENT_CHARS = 60_000


def format_registry_diff_comment(
    markdown: str,
    *,
    max_chars: int = DEFAULT_MAX_COMMENT_CHARS,
) -> str:
    """Return an idempotent PR comment body for a registry diff Markdown report."""
    if max_chars < 1_000:
        raise ValueError("max_chars must be at least 1000")

    report = markdown.strip() or "# Registry Diff\n\nNo registry diff content was produced."
    footer = (
        "\n\n---\n"
        "Generated by `skills-orchestrator registry diff`. "
        "The hidden marker above lets automation update this comment instead of posting duplicates.\n"
    )
    prefix = f"{REGISTRY_DIFF_COMMENT_MARKER}\n"
    body = f"{prefix}{report}{footer}"
    if len(body) <= max_chars:
        return body

    room = max_chars - len(prefix) - len(footer) - 120
    if room < 1:
        raise ValueError("max_chars is too small for registry diff comment framing")
    truncated = report[:room].rstrip()
    notice = (
        "\n\n_Registry diff comment truncated. Download the workflow artifact for the full report._"
    )
    return f"{prefix}{truncated}{notice}{footer}"


def format_registry_diff_comment_file(
    markdown_path: str | Path,
    *,
    max_chars: int = DEFAULT_MAX_COMMENT_CHARS,
) -> str:
    """Read a Markdown registry diff file and return the GitHub comment body."""
    content = Path(markdown_path).read_text(encoding="utf-8")
    return format_registry_diff_comment(content, max_chars=max_chars)
